--  Barcodable.com API
--  Barcodable.com API
--
--  The version of the OpenAPI document: 1.5.0
--  Contact: support@barcodable.com
--
--  NOTE: This package is auto generated by OpenAPI-Generator 4.3.0.
--  https://openapi-generator.tech
--  Do not edit the class manually.


package body .Models is

   use Swagger.Streams;



   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in InlineResponse400_Type) is
   begin
      Into.Start_Entity (Name);
      Into.Write_Entity ("message", Value.Message);
      Into.Write_Entity ("status", Value.Status);
      Into.End_Entity (Name);
   end Serialize;

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in InlineResponse400_Type_Vectors.Vector) is
   begin
      Into.Start_Array (Name);
      for Item of Value loop
         Serialize (Into, "", Item);
      end loop;
      Into.End_Array (Name);
   end Serialize;

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out InlineResponse400_Type) is
      Object : Swagger.Value_Type;
   begin
      Swagger.Streams.Deserialize (From, Name, Object);
      Swagger.Streams.Deserialize (Object, "message", Value.Message);
      Swagger.Streams.Deserialize (Object, "status", Value.Status);
   end Deserialize;

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out InlineResponse400_Type_Vectors.Vector) is
      List : Swagger.Value_Array_Type;
      Item : InlineResponse400_Type;
   begin
      Value.Clear;
      Swagger.Streams.Deserialize (From, Name, List);
      for Data of List loop
         Deserialize (Data, "", Item);
         Value.Append (Item);
      end loop;
   end Deserialize;




   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in InvalidCode_Type) is
   begin
      Into.Start_Entity (Name);
      Into.Write_Entity ("message", Value.Message);
      Into.Write_Entity ("status", Value.Status);
      Into.End_Entity (Name);
   end Serialize;

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in InvalidCode_Type_Vectors.Vector) is
   begin
      Into.Start_Array (Name);
      for Item of Value loop
         Serialize (Into, "", Item);
      end loop;
      Into.End_Array (Name);
   end Serialize;

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out InvalidCode_Type) is
      Object : Swagger.Value_Type;
   begin
      Swagger.Streams.Deserialize (From, Name, Object);
      Swagger.Streams.Deserialize (Object, "message", Value.Message);
      Swagger.Streams.Deserialize (Object, "status", Value.Status);
   end Deserialize;

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out InvalidCode_Type_Vectors.Vector) is
      List : Swagger.Value_Array_Type;
      Item : InvalidCode_Type;
   begin
      Value.Clear;
      Swagger.Streams.Deserialize (From, Name, List);
      for Data of List loop
         Deserialize (Data, "", Item);
         Value.Append (Item);
      end loop;
   end Deserialize;




   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in NotFound_Type) is
   begin
      Into.Start_Entity (Name);
      Into.Write_Entity ("message", Value.Message);
      Into.Write_Entity ("status", Value.Status);
      Into.End_Entity (Name);
   end Serialize;

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in NotFound_Type_Vectors.Vector) is
   begin
      Into.Start_Array (Name);
      for Item of Value loop
         Serialize (Into, "", Item);
      end loop;
      Into.End_Array (Name);
   end Serialize;

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out NotFound_Type) is
      Object : Swagger.Value_Type;
   begin
      Swagger.Streams.Deserialize (From, Name, Object);
      Swagger.Streams.Deserialize (Object, "message", Value.Message);
      Swagger.Streams.Deserialize (Object, "status", Value.Status);
   end Deserialize;

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out NotFound_Type_Vectors.Vector) is
      List : Swagger.Value_Array_Type;
      Item : NotFound_Type;
   begin
      Value.Clear;
      Swagger.Streams.Deserialize (From, Name, List);
      for Data of List loop
         Deserialize (Data, "", Item);
         Value.Append (Item);
      end loop;
   end Deserialize;




   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in InlineResponse200_Type) is
   begin
      Into.Start_Entity (Name);
      Serialize (Into, "upcs", Value.Upcs);
      Serialize (Into, "eans", Value.Eans);
      Serialize (Into, "asins", Value.Asins);
      Into.Write_Entity ("message", Value.Message);
      Into.End_Entity (Name);
   end Serialize;

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in InlineResponse200_Type_Vectors.Vector) is
   begin
      Into.Start_Array (Name);
      for Item of Value loop
         Serialize (Into, "", Item);
      end loop;
      Into.End_Array (Name);
   end Serialize;

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out InlineResponse200_Type) is
      Object : Swagger.Value_Type;
   begin
      Swagger.Streams.Deserialize (From, Name, Object);
      Swagger.Streams.Deserialize (Object, "upcs", Value.Upcs);
      Swagger.Streams.Deserialize (Object, "eans", Value.Eans);
      Swagger.Streams.Deserialize (Object, "asins", Value.Asins);
      Swagger.Streams.Deserialize (Object, "message", Value.Message);
   end Deserialize;

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out InlineResponse200_Type_Vectors.Vector) is
      List : Swagger.Value_Array_Type;
      Item : InlineResponse200_Type;
   begin
      Value.Clear;
      Swagger.Streams.Deserialize (From, Name, List);
      for Data of List loop
         Deserialize (Data, "", Item);
         Value.Append (Item);
      end loop;
   end Deserialize;




   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Item_Type) is
   begin
      Into.Start_Entity (Name);
      Into.Write_Entity ("upc", Value.Upc);
      Into.Write_Entity ("ean", Value.Ean);
      Into.Write_Entity ("isbn", Value.Isbn);
      Into.Write_Entity ("asin", Value.Asin);
      Into.Write_Entity ("title", Value.Title);
      Into.Write_Entity ("sku", Value.Sku);
      Into.Write_Entity ("mpn", Value.Mpn);
      Into.Write_Entity ("part_number", Value.Part_Number);
      Serialize (Into, "upcs", Value.Upcs);
      Into.Write_Entity ("description", Value.Description);
      Into.Write_Entity ("brand", Value.Brand);
      Into.Write_Entity ("manufacturer", Value.Manufacturer);
      Into.Write_Entity ("color", Value.Color);
      Serialize (Into, "new_price", Value.New_Price);
      Serialize (Into, "used_price", Value.Used_Price);
      Into.Write_Entity ("currency_code", Value.Currency_Code);
      Into.Write_Entity ("url", Value.Url);
      Serialize (Into, "features", Value.Features);
      Serialize (Into, "dimensions", Value.Dimensions);
      Serialize (Into, "images", Value.Images);
      Serialize (Into, "matched_items", Value.Matched_Items);
      Serialize (Into, "iso_country_codes", Value.Iso_Country_Codes);
      Into.Write_Entity ("company_name", Value.Company_Name);
      Into.Write_Entity ("company_address", Value.Company_Address);
      Serialize (Into, "categories", Value.Categories);
      Serialize (Into, "category_hierarchies", Value.Category_Hierarchies);
      Into.End_Entity (Name);
   end Serialize;

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Item_Type_Vectors.Vector) is
   begin
      Into.Start_Array (Name);
      for Item of Value loop
         Serialize (Into, "", Item);
      end loop;
      Into.End_Array (Name);
   end Serialize;

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Item_Type) is
      Object : Swagger.Value_Type;
   begin
      Swagger.Streams.Deserialize (From, Name, Object);
      Swagger.Streams.Deserialize (Object, "upc", Value.Upc);
      Swagger.Streams.Deserialize (Object, "ean", Value.Ean);
      Swagger.Streams.Deserialize (Object, "isbn", Value.Isbn);
      Swagger.Streams.Deserialize (Object, "asin", Value.Asin);
      Swagger.Streams.Deserialize (Object, "title", Value.Title);
      Swagger.Streams.Deserialize (Object, "sku", Value.Sku);
      Swagger.Streams.Deserialize (Object, "mpn", Value.Mpn);
      Swagger.Streams.Deserialize (Object, "part_number", Value.Part_Number);
      Swagger.Streams.Deserialize (Object, "upcs", Value.Upcs);
      Swagger.Streams.Deserialize (Object, "description", Value.Description);
      Swagger.Streams.Deserialize (Object, "brand", Value.Brand);
      Swagger.Streams.Deserialize (Object, "manufacturer", Value.Manufacturer);
      Swagger.Streams.Deserialize (Object, "color", Value.Color);
      Deserialize (Object, "new_price", Value.New_Price);
      Deserialize (Object, "used_price", Value.Used_Price);
      Swagger.Streams.Deserialize (Object, "currency_code", Value.Currency_Code);
      Swagger.Streams.Deserialize (Object, "url", Value.Url);
      Swagger.Streams.Deserialize (Object, "features", Value.Features);
      Deserialize (Object, "dimensions", Value.Dimensions);
      Swagger.Streams.Deserialize (Object, "images", Value.Images);
      Deserialize (Object, "matched_items", Value.Matched_Items);
      Swagger.Streams.Deserialize (Object, "iso_country_codes", Value.Iso_Country_Codes);
      Swagger.Streams.Deserialize (Object, "company_name", Value.Company_Name);
      Swagger.Streams.Deserialize (Object, "company_address", Value.Company_Address);
      Swagger.Streams.Deserialize (Object, "categories", Value.Categories);
      Swagger.Streams.Deserialize (Object, "category_hierarchies", Value.Category_Hierarchies);
   end Deserialize;

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Item_Type_Vectors.Vector) is
      List : Swagger.Value_Array_Type;
      Item : Item_Type;
   begin
      Value.Clear;
      Swagger.Streams.Deserialize (From, Name, List);
      for Data of List loop
         Deserialize (Data, "", Item);
         Value.Append (Item);
      end loop;
   end Deserialize;



end .Models;
