--  Barcodable.com API
--  Barcodable.com API
--
--  The version of the OpenAPI document: 1.5.0
--  Contact: support@barcodable.com
--
--  NOTE: This package is auto generated by OpenAPI-Generator 4.3.0.
--  https://openapi-generator.tech
--  Do not edit the class manually.

with Swagger.Streams;
with Ada.Containers.Vectors;
package .Models is



   type InlineResponse400_Type is
     record
       Message : Swagger.Nullable_UString;
       Status : Swagger.Nullable_Integer;
     end record;

   package InlineResponse400_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => InlineResponse400_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in InlineResponse400_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in InlineResponse400_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out InlineResponse400_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out InlineResponse400_Type_Vectors.Vector);




   type InvalidCode_Type is
     record
       Message : Swagger.Nullable_UString;
       Status : Swagger.Nullable_Integer;
     end record;

   package InvalidCode_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => InvalidCode_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in InvalidCode_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in InvalidCode_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out InvalidCode_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out InvalidCode_Type_Vectors.Vector);




   type NotFound_Type is
     record
       Message : Swagger.Nullable_UString;
       Status : Swagger.Nullable_Integer;
     end record;

   package NotFound_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => NotFound_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in NotFound_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in NotFound_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out NotFound_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out NotFound_Type_Vectors.Vector);




   type InlineResponse200_Type is
     record
       Upcs : Swagger.UString_Vectors.Vector;
       Eans : Swagger.UString_Vectors.Vector;
       Asins : Swagger.UString_Vectors.Vector;
       Message : Swagger.Nullable_UString;
     end record;

   package InlineResponse200_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => InlineResponse200_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in InlineResponse200_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in InlineResponse200_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out InlineResponse200_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out InlineResponse200_Type_Vectors.Vector);




   type Item_Type is
     record
       Upc : Swagger.Nullable_UString;
       Ean : Swagger.Nullable_UString;
       Isbn : Swagger.Nullable_UString;
       Asin : Swagger.Nullable_UString;
       Title : Swagger.Nullable_UString;
       Sku : Swagger.Nullable_UString;
       Mpn : Swagger.Nullable_UString;
       Part_Number : Swagger.Nullable_UString;
       Upcs : Swagger.UString_Vectors.Vector;
       Description : Swagger.Nullable_UString;
       Brand : Swagger.Nullable_UString;
       Manufacturer : Swagger.Nullable_UString;
       Color : Swagger.Nullable_UString;
       New_Price : Swagger.Number;
       Used_Price : Swagger.Number;
       Currency_Code : Swagger.Nullable_UString;
       Url : Swagger.Nullable_UString;
       Features : Swagger.UString_Vectors.Vector;
       Dimensions : Swagger.Object_Vectors.Vector;
       Images : Swagger.UString_Vectors.Vector;
       Matched_Items : Swagger.Object_Vectors.Vector;
       Iso_Country_Codes : Swagger.UString_Vectors.Vector;
       Company_Name : Swagger.Nullable_UString;
       Company_Address : Swagger.Nullable_UString;
       Categories : Swagger.UString_Vectors.Vector;
       Category_Hierarchies : Swagger.UString_Vectors.Vector;
     end record;

   package Item_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => Item_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Item_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Item_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Item_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Item_Type_Vectors.Vector);



end .Models;
