#
# Barcodable.com API
# Barcodable.com API
# Version: 1.5.0
# Contact: support@barcodable.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ProductLookupApi' {
    Context 'Get-ItemByASIN' {
        It 'Test Get-ItemByASIN' {
            #$TestResult = Invoke-PetApiGetPetById -Asin "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Get-ItemByEAN' {
        It 'Test Get-ItemByEAN' {
            #$TestResult = Invoke-PetApiGetPetById -Ean "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Get-ItemByUPC' {
        It 'Test Get-ItemByUPC' {
            #$TestResult = Invoke-PetApiGetPetById -Upc "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

}
