=begin
Barcodable.com API

Barcodable.com API

OpenAPI spec version: 1.5.0
Contact: support@barcodable.com
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class ProductLookupController < ApplicationController

  def get_item_by_asin
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_item_by_ean
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_item_by_upc
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
