/**
* Barcodable.com API
* Barcodable.com API
*
* The version of the OpenAPI document: 1.5.0
* Contact: support@barcodable.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param upcs A list of UPCs
 * @param eans A list of EANs
 * @param asins A list of ASINs
 * @param message 
 */

data class InlineResponse200 (
    /* A list of UPCs */
    @Json(name = "upcs")
    val upcs: kotlin.Array<kotlin.String>? = null,
    /* A list of EANs */
    @Json(name = "eans")
    val eans: kotlin.Array<kotlin.String>? = null,
    /* A list of ASINs */
    @Json(name = "asins")
    val asins: kotlin.Array<kotlin.String>? = null,
    @Json(name = "message")
    val message: kotlin.String? = null
)

