/**
* Barcodable.com API
* Barcodable.com API
*
* The version of the OpenAPI document: 1.5.0
* Contact: support@barcodable.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param message 
 * @param status 
 */

data class InlineResponse400 (
    @Json(name = "message")
    val message: kotlin.String? = null,
    @Json(name = "status")
    val status: kotlin.Int? = null
)

