/**
* Barcodable.com API
* Barcodable.com API
*
* The version of the OpenAPI document: 1.5.0
* Contact: support@barcodable.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param upc 
 * @param ean 
 * @param isbn 
 * @param asin 
 * @param title 
 * @param sku 
 * @param mpn 
 * @param partNumber 
 * @param upcs A list of matching upc codes.
 * @param description 
 * @param brand 
 * @param manufacturer 
 * @param color 
 * @param newPrice 
 * @param usedPrice 
 * @param currencyCode 
 * @param url 
 * @param features A list of product feature descriptions.
 * @param dimensions Product dimensions and weight.  ('meters', 'centimeters', 'millimeters', 'inches', 'feet', 'yards', 'ounces', 'pounds', 'grams', 'milligrams', 'kilograms')
 * @param images A list product images.
 * @param matchedItems Matched items for this product.
 * @param isoCountryCodes A list of country codes from which this item belongs.
 * @param companyName The company name registered to the product's UPC or EAN.
 * @param companyAddress The company address registered to the product's UPC or EAN.
 * @param categories A list of categories for this product.
 * @param categoryHierarchies A list of category hierarchies for this product. Categories are listed in order of generic category to most specific category.
 */

data class Item (
    @Json(name = "upc")
    val upc: kotlin.String? = null,
    @Json(name = "ean")
    val ean: kotlin.String? = null,
    @Json(name = "isbn")
    val isbn: kotlin.String? = null,
    @Json(name = "asin")
    val asin: kotlin.String? = null,
    @Json(name = "title")
    val title: kotlin.String? = null,
    @Json(name = "sku")
    val sku: kotlin.String? = null,
    @Json(name = "mpn")
    val mpn: kotlin.String? = null,
    @Json(name = "part_number")
    val partNumber: kotlin.String? = null,
    /* A list of matching upc codes. */
    @Json(name = "upcs")
    val upcs: kotlin.Array<kotlin.String>? = null,
    @Json(name = "description")
    val description: kotlin.String? = null,
    @Json(name = "brand")
    val brand: kotlin.String? = null,
    @Json(name = "manufacturer")
    val manufacturer: kotlin.String? = null,
    @Json(name = "color")
    val color: kotlin.String? = null,
    @Json(name = "new_price")
    val newPrice: java.math.BigDecimal? = null,
    @Json(name = "used_price")
    val usedPrice: java.math.BigDecimal? = null,
    @Json(name = "currency_code")
    val currencyCode: kotlin.String? = null,
    @Json(name = "url")
    val url: kotlin.String? = null,
    /* A list of product feature descriptions. */
    @Json(name = "features")
    val features: kotlin.Array<kotlin.String>? = null,
    /* Product dimensions and weight.  ('meters', 'centimeters', 'millimeters', 'inches', 'feet', 'yards', 'ounces', 'pounds', 'grams', 'milligrams', 'kilograms') */
    @Json(name = "dimensions")
    val dimensions: kotlin.Array<kotlin.Any>? = null,
    /* A list product images. */
    @Json(name = "images")
    val images: kotlin.Array<kotlin.String>? = null,
    /* Matched items for this product. */
    @Json(name = "matched_items")
    val matchedItems: kotlin.Array<kotlin.Any>? = null,
    /* A list of country codes from which this item belongs. */
    @Json(name = "iso_country_codes")
    val isoCountryCodes: kotlin.Array<kotlin.String>? = null,
    /* The company name registered to the product's UPC or EAN. */
    @Json(name = "company_name")
    val companyName: kotlin.String? = null,
    /* The company address registered to the product's UPC or EAN. */
    @Json(name = "company_address")
    val companyAddress: kotlin.String? = null,
    /* A list of categories for this product. */
    @Json(name = "categories")
    val categories: kotlin.Array<kotlin.String>? = null,
    /* A list of category hierarchies for this product. Categories are listed in order of generic category to most specific category. */
    @Json(name = "category_hierarchies")
    val categoryHierarchies: kotlin.Array<kotlin.String>? = null
)

