/**
 * Barcodable.com API
 * Barcodable.com API
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: support@barcodable.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ProductConversionApi.h
 *
 * 
 */

#ifndef ProductConversionApi_H_
#define ProductConversionApi_H_


#include <memory>
#include <utility>

#include <corvusoft/restbed/session.hpp>
#include <corvusoft/restbed/resource.hpp>
#include <corvusoft/restbed/service.hpp>

#include "Inline_response_200.h"
#include "Inline_response_400.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class  ProductConversionApi: public restbed::Service
{
public:
	ProductConversionApi();
	~ProductConversionApi();
	void startService(int const& port);
	void stopService();
};


/// <summary>
/// Convert between UPC, EAN, and ASIN product codes.
/// </summary>
/// <remarks>
/// Returns the converted UPC, EAN, and ASIN codes.
/// </remarks>
class  ProductConversionApiApiV1ConvertUpc | ean | asinResource: public restbed::Resource
{
public:
	ProductConversionApiApiV1ConvertUpc | ean | asinResource();
    virtual ~ProductConversionApiApiV1ConvertUpc | ean | asinResource();
    void GET_method_handler(const std::shared_ptr<restbed::Session> session);

	void set_handler_GET(
		std::function<std::pair<int, std::string>(
			std::string const &
		)> handler
	);


private:
	std::function<std::pair<int, std::string>(
		std::string const &
	)> handler_GET_;


	std::string upc_Pipe_ean_Pipe_asin{};
};


}
}
}
}

#endif /* ProductConversionApi_H_ */

