# coding: utf-8

"""
    Barcodable.com API

    Barcodable.com API  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@barcodable.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.item import Item  # noqa: E501
from openapi_client.rest import ApiException

class TestItem(unittest.TestCase):
    """Item unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Item
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.item.Item()  # noqa: E501
        if include_optional :
            return Item(
                upc = '190198155795', 
                ean = '190198155795', 
                isbn = '9780198155795', 
                asin = 'B01M1EXQY4', 
                title = 'Apple iPhone 7 Unlocked Phone 128 GB - US Version (Black)', 
                sku = '903061477', 
                mpn = 'A1660', 
                part_number = '14', 
                upcs = ["190198071835, 647627503790, 759776410383, 190198068507"], 
                description = 'The latest iPhone with advanced camera, better battery life, immersive speakers and water resistance!', 
                brand = 'Apple', 
                manufacturer = 'Apple', 
                color = 'Black', 
                new_price = 799.95, 
                used_price = 659.95, 
                currency_code = 'USD', 
                url = 'https://www.amazon.com/Apple-iPhone-Unlocked-Phone-128/dp/B01M1EXQY4', 
                features = ["Smooth, continuous unibody design. 3D Touch, Live Photos, an A9 chip, advanced cameras, and a 4.7-inch Retina HD display. And so much more.","The most advanced chip ever in a smartphone is even faster and now features an integrated M9 motion coprocessor."], 
                dimensions = [
                    None
                    ], 
                images = ["https://images-na.ssl-images-amazon.com/images/I/317AuSoRaHL.jpg","https://images-na.ssl-images-amazon.com/images/I/41Whf3N9i2L.jpg"], 
                matched_items = [
                    None
                    ], 
                iso_country_codes = ["US","GB"], 
                company_name = 'Apple Inc.', 
                company_address = '101 Infinite Loop, Cupertino, CA 95014', 
                categories = ["Unlocked Cell Phones","Electronics"], 
                category_hierarchies = [["Cell Phones & Accessories","Cell Phones","Unlocked Cell Phones"]]
            )
        else :
            return Item(
        )

    def testItem(self):
        """Test Item"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
