# coding: utf-8

"""
    Barcodable.com API

    Barcodable.com API  # noqa: E501

    OpenAPI spec version: 1.5.0
    Contact: support@barcodable.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.not_found import NotFound  # noqa: E501
from openapi_client.rest import ApiException


class TestNotFound(unittest.TestCase):
    """NotFound unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotFound(self):
        """Test NotFound"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.not_found.NotFound()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
