# coding: utf-8

"""
    Barcodable.com API

    Barcodable.com API  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@barcodable.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.product_lookup_api import ProductLookupApi  # noqa: E501
from openapi_client.rest import ApiException


class TestProductLookupApi(unittest.TestCase):
    """ProductLookupApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.product_lookup_api.ProductLookupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_item_by_asin(self):
        """Test case for get_item_by_asin

        Find item by asin code  # noqa: E501
        """
        pass

    def test_get_item_by_ean(self):
        """Test case for get_item_by_ean

        Find item by UPC code  # noqa: E501
        """
        pass

    def test_get_item_by_upc(self):
        """Test case for get_item_by_upc

        Find item by UPC code  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
