{-
   Barcodable.com API

   Barcodable.com API

   OpenAPI Version: 3.0.0
   Barcodable.com API API version: 1.5.0
   Contact: support@barcodable.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : Barcodable.com.API.ProductConversion
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module Barcodable.com.API.ProductConversion where

import Barcodable.com.Core
import Barcodable.com.MimeTypes
import Barcodable.com.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** ProductConversion

-- *** convertCode

-- | @GET \/api\/v1\/convert\/{upc | ean | asin}@
-- 
-- Convert between UPC, EAN, and ASIN product codes.
-- 
-- Returns the converted UPC, EAN, and ASIN codes.
-- 
convertCode 
  :: UpcEanAsin -- ^ "upcEanAsin" -  UPC, EAN, or ASIN
  -> comRequest ConvertCode MimeNoContent InlineResponse200 MimeJSON
convertCode (UpcEanAsin upcEanAsin) =
  _mkRequest "GET" ["/api/v1/convert/",toPath upcEanAsin,"|",toPath upcEanAsin,"|",toPath upcEanAsin]

data ConvertCode  

-- | @application/json@
instance Produces ConvertCode MimeJSON

