#
# Barcodable.com API
# 
# Barcodable.com API
# The version of the OpenAPI document: 1.5.0
# Contact: support@barcodable.com
# Generated by: https://openapi-generator.tech
#

import json
import tables


type InlineResponse400* = object
  ## 
  message*: string
  status*: int
