/**
 * Barcodable.com API
 * Barcodable.com API
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: support@barcodable.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ProductLookupApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_ProductLookupApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_ProductLookupApi_H_


#include "../ApiClient.h"

#include "Invalid_code.h"
#include "Item.h"
#include "Not_found.h"
#include <cpprest/details/basic_types.h>


#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  ProductLookupApi 
{
public:

    explicit ProductLookupApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~ProductLookupApi();

    /// <summary>
    /// Find item by asin code
    /// </summary>
    /// <remarks>
    /// Returns a single item
    /// </remarks>
    /// <param name="asin">ASIN code of item to return</param>
    pplx::task<std::shared_ptr<Item>> getItemByASIN(
        utility::string_t asin
    ) const;
    /// <summary>
    /// Find item by UPC code
    /// </summary>
    /// <remarks>
    /// Returns a single item
    /// </remarks>
    /// <param name="ean">EAN code of item to return</param>
    pplx::task<std::shared_ptr<Item>> getItemByEAN(
        utility::string_t ean
    ) const;
    /// <summary>
    /// Find item by UPC code
    /// </summary>
    /// <remarks>
    /// Returns a single item
    /// </remarks>
    /// <param name="upc">UPC code of item to return</param>
    pplx::task<std::shared_ptr<Item>> getItemByUPC(
        utility::string_t upc
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_ProductLookupApi_H_ */

