/**
 * 
 * Barcodable.com API
 * 
 * 
 * Barcodable.com API
 * 
 * Version: 1.5.0
 * Contact: support@barcodable.com
 * Generated by OpenAPI Generator: https://openapi-generator.tech
 */

// package openapi3graphql-server

// product_conversion_api

export default {
    Query: {

        // @return InlineResponse200
        ConvertCode: ($upcEanAsin) => {
            return {
                "upcEanAsin": "upcEanAsin_example"
            };
        },

    },

    Mutation: {

    }
}