/*
 * Barcodable.com API
 *
 * Barcodable.com API
 *
 * API version: 1.5.0
 * Contact: support@barcodable.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// ProductLookupApiService is a service that implents the logic for the ProductLookupApiServicer
// This service should implement the business logic for every endpoint for the ProductLookupApi API. 
// Include any external packages or services that will be required by this service.
type ProductLookupApiService struct {
}

// NewProductLookupApiService creates a default api service
func NewProductLookupApiService() ProductLookupApiServicer {
	return &ProductLookupApiService{}
}

// GetItemByASIN - Find item by asin code
func (s *ProductLookupApiService) GetItemByASIN(asin string) (interface{}, error) {
	// TODO - update GetItemByASIN with the required logic for this service method.
	// Add api_product_lookup_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetItemByASIN' not implemented")
}

// GetItemByEAN - Find item by UPC code
func (s *ProductLookupApiService) GetItemByEAN(ean string) (interface{}, error) {
	// TODO - update GetItemByEAN with the required logic for this service method.
	// Add api_product_lookup_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetItemByEAN' not implemented")
}

// GetItemByUPC - Find item by UPC code
func (s *ProductLookupApiService) GetItemByUPC(upc string) (interface{}, error) {
	// TODO - update GetItemByUPC with the required logic for this service method.
	// Add api_product_lookup_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetItemByUPC' not implemented")
}
