/*
 * Barcodable.com API
 *
 * Barcodable.com API
 *
 * API version: 1.5.0
 * Contact: support@barcodable.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		"GET",
		"/magicCashew/barcodable/1.0.0/",
		Index,
	},

	{
		"ConvertCode",
		strings.ToUpper("Get"),
		"/magicCashew/barcodable/1.0.0/api/v1/convert/{upc | ean | asin}",
		ConvertCode,
	},

	{
		"GetItemByASIN",
		strings.ToUpper("Get"),
		"/magicCashew/barcodable/1.0.0/api/v1/asin/{asin}",
		GetItemByASIN,
	},

	{
		"GetItemByEAN",
		strings.ToUpper("Get"),
		"/magicCashew/barcodable/1.0.0/api/v1/ean/{ean}",
		GetItemByEAN,
	},

	{
		"GetItemByUPC",
		strings.ToUpper("Get"),
		"/magicCashew/barcodable/1.0.0/api/v1/upc/{upc}",
		GetItemByUPC,
	},
}
