{-
   Barcodable.com API
   Barcodable.com API

   OpenAPI spec version: 1.5.0
   Contact: support@barcodable.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Request.ProductConversion exposing (convertCode)

import Data.InlineResponse200 as InlineResponse200 exposing (InlineResponse200)
import Data.InlineResponse400 as InlineResponse400 exposing (InlineResponse400)
import Dict
import Http
import Json.Decode as Decode
import Url.Builder as Url


basePath : String
basePath =
    "https://virtserver.swaggerhub.com/mindviser/barcodable/1.0.0"


{-| Returns the converted UPC, EAN, and ASIN codes.
-}
convertCode :
    { onSend : Result Http.Error InlineResponse200 -> msg



    , upc Pipe ean Pipe asin : String

    }
    -> Cmd msg
convertCode params =
    Http.request
        { method = "GET"
        , headers = []
        , url = Url.crossOrigin basePath
            ["api", "v1", "convert", {upc | ean | asin}]
            []
        , body = Http.emptyBody
        , expect = Http.expectJson params.onSend InlineResponse200.decoder
        , timeout = Just 30000
        , tracker = Nothing
        }
