--[[
  Barcodable.com API
 
  Barcodable.com API
 
  The version of the OpenAPI document: 1.5.0
  Contact: support@barcodable.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.inline_response_400
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("inline_response_400", function()
  local openapiclient_inline_response_400 = require "openapiclient.model.inline_response_400"

  -- unit tests for the property 'message'
  describe("property message test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'status'
  describe("property status test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
