/**
* Barcodable.com API
* Barcodable.com API
*
* OpenAPI spec version: 1.5.0
* Contact: support@barcodable.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* ProductLookupApiImpl.h
*
* 
*/

#ifndef PRODUCT_LOOKUP_API_IMPL_H_
#define PRODUCT_LOOKUP_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <ProductLookupApi.h>

#include <pistache/optional.h>

#include "Invalid_code.h"
#include "Item.h"
#include "Not_found.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class ProductLookupApiImpl : public org::openapitools::server::api::ProductLookupApi {
public:
    ProductLookupApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~ProductLookupApiImpl() {}

    void get_item_by_asin(const std::string &asin, Pistache::Http::ResponseWriter &response);
    void get_item_by_ean(const std::string &ean, Pistache::Http::ResponseWriter &response);
    void get_item_by_upc(const std::string &upc, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif