# Barcodable.com API
#
# Barcodable.com API
#
# OpenAPI spec version: 1.5.0
# Contact: support@barcodable.com
# Generated by: https://openapi-generator.tech


#' InlineResponse200 Class
#'
#' @field upcs 
#' @field eans 
#' @field asins 
#' @field message 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse200 <- R6::R6Class(
  'InlineResponse200',
  public = list(
    `upcs` = NULL,
    `eans` = NULL,
    `asins` = NULL,
    `message` = NULL,
    initialize = function(`upcs`, `eans`, `asins`, `message`){
      if (!missing(`upcs`)) {
                stopifnot(is.vector(`upcs`), length(`upcs`) != 0)
                sapply(`upcs`, function(x) stopifnot(is.character(x)))
        self$`upcs` <- `upcs`
      }
      if (!missing(`eans`)) {
                stopifnot(is.vector(`eans`), length(`eans`) != 0)
                sapply(`eans`, function(x) stopifnot(is.character(x)))
        self$`eans` <- `eans`
      }
      if (!missing(`asins`)) {
                stopifnot(is.vector(`asins`), length(`asins`) != 0)
                sapply(`asins`, function(x) stopifnot(is.character(x)))
        self$`asins` <- `asins`
      }
      if (!missing(`message`)) {
                stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
    },
    toJSON = function() {
      InlineResponse200Object <- list()
      if (!is.null(self$`upcs`)) {
        InlineResponse200Object[['upcs']] <-
                self$`upcs`
      }
      if (!is.null(self$`eans`)) {
        InlineResponse200Object[['eans']] <-
                self$`eans`
      }
      if (!is.null(self$`asins`)) {
        InlineResponse200Object[['asins']] <-
                self$`asins`
      }
      if (!is.null(self$`message`)) {
        InlineResponse200Object[['message']] <-
                self$`message`
      }

      InlineResponse200Object
    },
    fromJSON = function(InlineResponse200Json) {
      InlineResponse200Object <- jsonlite::fromJSON(InlineResponse200Json)
      if (!is.null(InlineResponse200Object$`upcs`)) {
                self$`upcs` <- InlineResponse200Object$`upcs`
      }
      if (!is.null(InlineResponse200Object$`eans`)) {
                self$`eans` <- InlineResponse200Object$`eans`
      }
      if (!is.null(InlineResponse200Object$`asins`)) {
                self$`asins` <- InlineResponse200Object$`asins`
      }
      if (!is.null(InlineResponse200Object$`message`)) {
                self$`message` <- InlineResponse200Object$`message`
      }
    },
    toJSONString = function() {
       outstring <- sprintf(
        '{
           "upcs":
                      
                      ["%s"]
                  
              ,
           "eans":
                      
                      ["%s"]
                  
              ,
           "asins":
                      
                      ["%s"]
                  
              ,
           "message":
                      
                      "%s"
                  
              
        }',
                paste0(self$`upcs`, collapse='","'),
                paste0(self$`eans`, collapse='","'),
                paste0(self$`asins`, collapse='","'),
                self$`message`
      )
      gsub("[\r\n]| ", "", outstring)
    },
    fromJSONString = function(InlineResponse200Json) {
      InlineResponse200Object <- jsonlite::fromJSON(InlineResponse200Json)
              self$`upcs` <- InlineResponse200Object$`upcs`
              self$`eans` <- InlineResponse200Object$`eans`
              self$`asins` <- InlineResponse200Object$`asins`
              self$`message` <- InlineResponse200Object$`message`
    }
  )
)
