# Barcodable.com API
#
# Barcodable.com API
#
# The version of the OpenAPI document: 1.5.0
# Contact: support@barcodable.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InvalidCode
#' @description InvalidCode Class
#' @format An \code{R6Class} generator object
#' @field message  character [optional]
#'
#' @field status  integer [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InvalidCode <- R6::R6Class(
  'InvalidCode',
  public = list(
    `message` = NULL,
    `status` = NULL,
    initialize = function(`message`=NULL, `status`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!is.null(`status`)) {
        stopifnot(is.numeric(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
    },
    toJSON = function() {
      InvalidCodeObject <- list()
      if (!is.null(self$`message`)) {
        InvalidCodeObject[['message']] <-
          self$`message`
      }
      if (!is.null(self$`status`)) {
        InvalidCodeObject[['status']] <-
          self$`status`
      }

      InvalidCodeObject
    },
    fromJSON = function(InvalidCodeJson) {
      InvalidCodeObject <- jsonlite::fromJSON(InvalidCodeJson)
      if (!is.null(InvalidCodeObject$`message`)) {
        self$`message` <- InvalidCodeObject$`message`
      }
      if (!is.null(InvalidCodeObject$`status`)) {
        self$`status` <- InvalidCodeObject$`status`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`message`)) {
        sprintf(
        '"message":
          "%s"
                ',
        self$`message`
        )},
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
          %d
                ',
        self$`status`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InvalidCodeJson) {
      InvalidCodeObject <- jsonlite::fromJSON(InvalidCodeJson)
      self$`message` <- InvalidCodeObject$`message`
      self$`status` <- InvalidCodeObject$`status`
      self
    }
  )
)
