# Barcodable.com API
#
# Barcodable.com API
#
# OpenAPI spec version: 1.5.0
# Contact: support@barcodable.com
# Generated by: https://openapi-generator.tech


#' NotFound Class
#'
#' @field message 
#' @field status 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
NotFound <- R6::R6Class(
  'NotFound',
  public = list(
    `message` = NULL,
    `status` = NULL,
    initialize = function(`message`, `status`){
      if (!missing(`message`)) {
                stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!missing(`status`)) {
                stopifnot(is.numeric(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
    },
    toJSON = function() {
      NotFoundObject <- list()
      if (!is.null(self$`message`)) {
        NotFoundObject[['message']] <-
                self$`message`
      }
      if (!is.null(self$`status`)) {
        NotFoundObject[['status']] <-
                self$`status`
      }

      NotFoundObject
    },
    fromJSON = function(NotFoundJson) {
      NotFoundObject <- jsonlite::fromJSON(NotFoundJson)
      if (!is.null(NotFoundObject$`message`)) {
                self$`message` <- NotFoundObject$`message`
      }
      if (!is.null(NotFoundObject$`status`)) {
                self$`status` <- NotFoundObject$`status`
      }
    },
    toJSONString = function() {
       outstring <- sprintf(
        '{
           "message":
                      
                      "%s"
                  
              ,
           "status":
                      %d
                      
                  
              
        }',
                self$`message`,
                self$`status`
      )
      gsub("[\r\n]| ", "", outstring)
    },
    fromJSONString = function(NotFoundJson) {
      NotFoundObject <- jsonlite::fromJSON(NotFoundJson)
              self$`message` <- NotFoundObject$`message`
              self$`status` <- NotFoundObject$`status`
    }
  )
)
