# Barcodable.com API
#
# Barcodable.com API
#
# The version of the OpenAPI document: 1.5.0
# Contact: support@barcodable.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ProductConversion operations
#' @description openapi.ProductConversion
#' @format An \code{R6Class} generator object
#' @field apiClient Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ ConvertCode } \emph{ Convert between UPC, EAN, and ASIN product codes. }
#' Returns the converted UPC, EAN, and ASIN codes.
#'
#' \itemize{
#' \item \emph{ @param } upc...ean...asin character
#' \item \emph{ @returnType } \link{InlineResponse200} \cr
#'
#'
#' \item status code : 200 | successful operation
#'
#' \item return type : InlineResponse200 
#' \item response headers :
#'
#' \tabular{ll}{
#' X-ValidAuthorization \tab A boolean indicating whether the API key in use is valid. Requests with an invalid subscription, incorrect key, or no key will return &#39;false&#39;. \cr
#' X-RateLimit-Limit \tab An integer specifying the number of requests available per day. This number is definied by your subscription plan. \cr
#' X-RateLimit-Remaining \tab An integer specifying the number of remaining requests per day. \cr
#' X-RateLimit-Reset \tab A timestamp specifying the time in which the daily rate limit is reset. \cr
#' }
#' \item status code : 400 | search results matching criteria
#'
#' \item return type : InlineResponse400 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  ConvertCode  ####################
#'
#' library(openapi)
#' var.upc...ean...asin <- 'upc...ean...asin_example' # character | UPC, EAN, or ASIN
#'
#' #Convert between UPC, EAN, and ASIN product codes.
#' api.instance <- ProductConversionApi$new()
#'
#' result <- api.instance$ConvertCode(var.upc...ean...asin)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom caTools base64encode
#' @export
ProductConversionApi <- R6::R6Class(
  'ProductConversionApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    ConvertCode = function(upc...ean...asin, ...){
      apiResponse <- self$ConvertCodeWithHttpInfo(upc...ean...asin, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ConvertCodeWithHttpInfo = function(upc...ean...asin, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`upc...ean...asin`)) {
        stop("Missing required parameter `upc...ean...asin`.")
      }

      urlPath <- "/api/v1/convert/{upc | ean | asin}"
      if (!missing(`upc...ean...asin`)) {
        urlPath <- gsub(paste0("\\{", "upc | ean | asin", "\\}"), URLencode(as.character(`upc...ean...asin`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse200", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    }
  )
)
