/**
 * Barcodable.com API
 * Barcodable.com API
 *
 * OpenAPI spec version: 1.5.0
 * Contact: support@barcodable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.swagger.client.model
import play.api.libs.json._

case class InlineResponse200 (
            /* A list of UPCs */
                  upcs: Option[Seq[String]],
            /* A list of EANs */
                  eans: Option[Seq[String]],
            /* A list of ASINs */
                  asins: Option[Seq[String]],
                  message: Option[String]
)

object InlineResponse200 {
implicit val format: Format[InlineResponse200] = Json.format
}

