/**
 * Barcodable.com API
 * Barcodable.com API
 *
 * OpenAPI spec version: 1.5.0
 * Contact: support@barcodable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class InlineResponse200 {
    /**
    * A list of UPCs
    */
    'upcs'?: Array<string>;
    /**
    * A list of EANs
    */
    'eans'?: Array<string>;
    /**
    * A list of ASINs
    */
    'asins'?: Array<string>;
    'message'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "upcs",
            "baseName": "upcs",
            "type": "Array<string>"
        },
        {
            "name": "eans",
            "baseName": "eans",
            "type": "Array<string>"
        },
        {
            "name": "asins",
            "baseName": "asins",
            "type": "Array<string>"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse200.attributeTypeMap;
    }
}

