(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* A list of UPCs *)
    upcs: string list;
    (* A list of EANs *)
    eans: string list;
    (* A list of ASINs *)
    asins: string list;
    message: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    upcs = [];
    eans = [];
    asins = [];
    message = None;
}

