<?php

/**
 * Barcodable.com API
 * Barcodable.com API
 *
 * OpenAPI spec version: 1.5.0
 * Contact: support@barcodable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Barcodable.com API
 * @version 1.5.0
 */

$router->get('/', function () use ($router) {
    return $router->app->version();
});

/**
 * get convertCode
 * Summary: Convert between UPC, EAN, and ASIN product codes.
 * Notes: Returns the converted UPC, EAN, and ASIN codes.
 */
$router->get('/mindviser/barcodable/1.0.0/api/v1/convert/{upc | ean | asin}', 'ProductConversionApi@convertCode');
/**
 * get getItemByASIN
 * Summary: Find item by asin code
 * Notes: Returns a single item
 */
$router->get('/mindviser/barcodable/1.0.0/api/v1/asin/{asin}', 'ProductLookupApi@getItemByASIN');
/**
 * get getItemByEAN
 * Summary: Find item by UPC code
 * Notes: Returns a single item
 */
$router->get('/mindviser/barcodable/1.0.0/api/v1/ean/{ean}', 'ProductLookupApi@getItemByEAN');
/**
 * get getItemByUPC
 * Summary: Find item by UPC code
 * Notes: Returns a single item
 */
$router->get('/mindviser/barcodable/1.0.0/api/v1/upc/{upc}', 'ProductLookupApi@getItemByUPC');

