/**
 * Barcodable.com API
 * Barcodable.com API
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: support@barcodable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class Item(
  upc: Option[String] = None,
  ean: Option[String] = None,
  isbn: Option[String] = None,
  asin: Option[String] = None,
  title: Option[String] = None,
  sku: Option[String] = None,
  mpn: Option[String] = None,
  partNumber: Option[String] = None,
  /* A list of matching upc codes. */
  upcs: Option[Seq[String]] = None,
  description: Option[String] = None,
  brand: Option[String] = None,
  manufacturer: Option[String] = None,
  color: Option[String] = None,
  newPrice: Option[Double] = None,
  usedPrice: Option[Double] = None,
  currencyCode: Option[String] = None,
  url: Option[String] = None,
  /* A list of product feature descriptions. */
  features: Option[Seq[String]] = None,
  /* Product dimensions and weight.  ('meters', 'centimeters', 'millimeters', 'inches', 'feet', 'yards', 'ounces', 'pounds', 'grams', 'milligrams', 'kilograms') */
  dimensions: Option[Seq[Any]] = None,
  /* A list product images. */
  images: Option[Seq[String]] = None,
  /* Matched items for this product. */
  matchedItems: Option[Seq[Any]] = None,
  /* A list of country codes from which this item belongs. */
  isoCountryCodes: Option[Seq[String]] = None,
  /* The company name registered to the product's UPC or EAN. */
  companyName: Option[String] = None,
  /* The company address registered to the product's UPC or EAN. */
  companyAddress: Option[String] = None,
  /* A list of categories for this product. */
  categories: Option[Seq[String]] = None,
  /* A list of category hierarchies for this product. Categories are listed in order of generic category to most specific category. */
  categoryHierarchies: Option[Seq[String]] = None
) extends ApiModel


