#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Barcodable.com API
* Barcodable.com API
*
* The version of the OpenAPI document: 1.5.0
* Contact: support@barcodable.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIInlineResponse200
@end

@interface OAIInlineResponse200 : OAIObject

/* A list of UPCs [optional]
 */
@property(nonatomic) NSArray<NSString*>* upcs;
/* A list of EANs [optional]
 */
@property(nonatomic) NSArray<NSString*>* eans;
/* A list of ASINs [optional]
 */
@property(nonatomic) NSArray<NSString*>* asins;

@property(nonatomic) NSString* message;

@end
