/*
 * Barcodable.com API
 *
 * Barcodable.com API
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: support@barcodable.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse200 {
    /// A list of UPCs
    #[serde(rename = "upcs", skip_serializing_if = "Option::is_none")]
    pub upcs: Option<Vec<String>>,
    /// A list of EANs
    #[serde(rename = "eans", skip_serializing_if = "Option::is_none")]
    pub eans: Option<Vec<String>>,
    /// A list of ASINs
    #[serde(rename = "asins", skip_serializing_if = "Option::is_none")]
    pub asins: Option<Vec<String>>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl InlineResponse200 {
    pub fn new() -> InlineResponse200 {
        InlineResponse200 {
            upcs: None,
            eans: None,
            asins: None,
            message: None,
        }
    }
}


