/**
* Barcodable.com API
* Barcodable.com API
*
* The version of the OpenAPI document: 1.5.0
* Contact: support@barcodable.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.api.model


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param upcs A list of UPCs
 * @param eans A list of EANs
 * @param asins A list of ASINs
 * @param message 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class InlineResponse200 (
    /* A list of UPCs */
    val upcs: kotlin.Array<kotlin.String>? = null,
    /* A list of EANs */
    val eans: kotlin.Array<kotlin.String>? = null,
    /* A list of ASINs */
    val asins: kotlin.Array<kotlin.String>? = null,
    val message: kotlin.String? = null
) {

}

