#
# Barcodable.com API
# Barcodable.com API
# Version: 1.5.0
# Contact: support@barcodable.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Upc
No description available.

.PARAMETER Ean
No description available.

.PARAMETER Isbn
No description available.

.PARAMETER Asin
No description available.

.PARAMETER Title
No description available.

.PARAMETER Sku
No description available.

.PARAMETER Mpn
No description available.

.PARAMETER PartNumber
No description available.

.PARAMETER Upcs
A list of matching upc codes.

.PARAMETER Description
No description available.

.PARAMETER Brand
No description available.

.PARAMETER Manufacturer
No description available.

.PARAMETER Color
No description available.

.PARAMETER NewPrice
No description available.

.PARAMETER UsedPrice
No description available.

.PARAMETER CurrencyCode
No description available.

.PARAMETER Url
No description available.

.PARAMETER Features
A list of product feature descriptions.

.PARAMETER Dimensions
Product dimensions and weight.  ('meters', 'centimeters', 'millimeters', 'inches', 'feet', 'yards', 'ounces', 'pounds', 'grams', 'milligrams', 'kilograms')

.PARAMETER Images
A list product images.

.PARAMETER MatchedItems
Matched items for this product.

.PARAMETER IsoCountryCodes
A list of country codes from which this item belongs.

.PARAMETER CompanyName
The company name registered to the product's UPC or EAN.

.PARAMETER CompanyAddress
The company address registered to the product's UPC or EAN.

.PARAMETER Categories
A list of categories for this product.

.PARAMETER CategoryHierarchies
A list of category hierarchies for this product. Categories are listed in order of generic category to most specific category.

.OUTPUTS

Item<PSCustomObject>
#>

function New-Item {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Upc},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Ean},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Isbn},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Asin},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Title},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Sku},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Mpn},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${PartNumber},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Upcs},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Brand},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Manufacturer},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Color},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${NewPrice},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${UsedPrice},
        [Parameter(Position = 15, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CurrencyCode},
        [Parameter(Position = 16, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Url},
        [Parameter(Position = 17, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Features},
        [Parameter(Position = 18, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Dimensions},
        [Parameter(Position = 19, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Images},
        [Parameter(Position = 20, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${MatchedItems},
        [Parameter(Position = 21, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${IsoCountryCodes},
        [Parameter(Position = 22, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CompanyName},
        [Parameter(Position = 23, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CompanyAddress},
        [Parameter(Position = 24, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Categories},
        [Parameter(Position = 25, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${CategoryHierarchies}
    )

    Process {
        'Creating object: PSOpenAPITools => Item' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $PSO = [PSCustomObject]@{
            "upc" = ${Upc}
            "ean" = ${Ean}
            "isbn" = ${Isbn}
            "asin" = ${Asin}
            "title" = ${Title}
            "sku" = ${Sku}
            "mpn" = ${Mpn}
            "part_number" = ${PartNumber}
            "upcs" = ${Upcs}
            "description" = ${Description}
            "brand" = ${Brand}
            "manufacturer" = ${Manufacturer}
            "color" = ${Color}
            "new_price" = ${NewPrice}
            "used_price" = ${UsedPrice}
            "currency_code" = ${CurrencyCode}
            "url" = ${Url}
            "features" = ${Features}
            "dimensions" = ${Dimensions}
            "images" = ${Images}
            "matched_items" = ${MatchedItems}
            "iso_country_codes" = ${IsoCountryCodes}
            "company_name" = ${CompanyName}
            "company_address" = ${CompanyAddress}
            "categories" = ${Categories}
            "category_hierarchies" = ${CategoryHierarchies}
        }

        return $PSO
    }
}
