/**
 * Barcodable.com API
 * Barcodable.com API
 *
 * OpenAPI spec version: 1.5.0
 * Contact: support@barcodable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BarcodablecomApi);
  }
}(this, function(expect, BarcodablecomApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BarcodablecomApi.ProductLookupApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductLookupApi', function() {
    describe('getItemByASIN', function() {
      it('should call getItemByASIN successfully', function(done) {
        //uncomment below and update the code to test getItemByASIN
        //instance.getItemByASIN(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getItemByEAN', function() {
      it('should call getItemByEAN successfully', function(done) {
        //uncomment below and update the code to test getItemByEAN
        //instance.getItemByEAN(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getItemByUPC', function() {
      it('should call getItemByUPC successfully', function(done) {
        //uncomment below and update the code to test getItemByUPC
        //instance.getItemByUPC(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
