// tslint:disable
/**
 * Barcodable.com API
 * Barcodable.com API
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: support@barcodable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface InvalidCode
 */
export interface InvalidCode {
    /**
     * @type {string}
     * @memberof InvalidCode
     */
    message?: string;
    /**
     * @type {number}
     * @memberof InvalidCode
     */
    status?: number;
}
