// tslint:disable
/**
 * Barcodable.com API
 * Barcodable.com API
 *
 * OpenAPI spec version: 1.5.0
 * Contact: support@barcodable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Item
 */
export interface Item {
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    upc?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    ean?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    isbn?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    asin?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    sku?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    mpn?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    partNumber?: string;
    /**
     * A list of matching upc codes.
     * @type {Array<string>}
     * @memberof Item
     */
    upcs?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    brand?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    manufacturer?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    color?: string;
    /**
     * 
     * @type {number}
     * @memberof Item
     */
    newPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof Item
     */
    usedPrice?: number;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    currencyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    url?: string;
    /**
     * A list of product feature descriptions.
     * @type {Array<string>}
     * @memberof Item
     */
    features?: Array<string>;
    /**
     * Product dimensions and weight.  ('meters', 'centimeters', 'millimeters', 'inches', 'feet', 'yards', 'ounces', 'pounds', 'grams', 'milligrams', 'kilograms')
     * @type {Array<any>}
     * @memberof Item
     */
    dimensions?: Array<any>;
    /**
     * A list product images.
     * @type {Array<string>}
     * @memberof Item
     */
    images?: Array<string>;
    /**
     * Matched items for this product.
     * @type {Array<any>}
     * @memberof Item
     */
    matchedItems?: Array<any>;
    /**
     * A list of country codes from which this item belongs.
     * @type {Array<string>}
     * @memberof Item
     */
    isoCountryCodes?: Array<string>;
    /**
     * The company name registered to the product's UPC or EAN.
     * @type {string}
     * @memberof Item
     */
    companyName?: string;
    /**
     * The company address registered to the product's UPC or EAN.
     * @type {string}
     * @memberof Item
     */
    companyAddress?: string;
    /**
     * A list of categories for this product.
     * @type {Array<string>}
     * @memberof Item
     */
    categories?: Array<string>;
    /**
     * A list of category hierarchies for this product. Categories are listed in order of generic category to most specific category.
     * @type {Array<string>}
     * @memberof Item
     */
    categoryHierarchies?: Array<string>;
}
