//
// InlineResponse200.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct InlineResponse200: Codable {

    /** A list of UPCs */
    public var upcs: [String]?
    /** A list of EANs */
    public var eans: [String]?
    /** A list of ASINs */
    public var asins: [String]?
    public var message: String?

    public init(upcs: [String]?, eans: [String]?, asins: [String]?, message: String?) {
        self.upcs = upcs
        self.eans = eans
        self.asins = asins
        self.message = message
    }


}

