/**
 * Barcodable.com API
 * Barcodable.com API
 *
 * OpenAPI spec version: 1.5.0
 * Contact: support@barcodable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */

package org.openapitools.server.model

case class InlineResponse200(
  /* A list of UPCs */
  upcs: Option[List[String]],

  /* A list of EANs */
  eans: Option[List[String]],

  /* A list of ASINs */
  asins: Option[List[String]],

  message: Option[String]

 )
