#
# Barcodable.com API
# Barcodable.com API
# Version: 1.5.0
# Contact: support@barcodable.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NotFound' {
    Context 'NotFound' {
        It 'New-NotFound' {
            # a simple test to create an object
            #$NewObject = New-NotFound -Message "TEST_VALUE" -Status "TEST_VALUE"
            #$NewObject | Should BeOfType NotFound
            #$NewObject.property | Should Be 0
        }
    }
}
