<?php
/**
 * InlineResponse200
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Barcodable.com API
 *
 * Barcodable.com API
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: support@barcodable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the InlineResponse200 model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class InlineResponse200 
{
        /**
     * A list of UPCs
     *
     * @var string[]|null
     * @SerializedName("upcs")
     * @Assert\All({
     *   @Assert\Type("string")
     * })
     * @Type("array<string>")
     */
    protected $upcs;

    /**
     * A list of EANs
     *
     * @var string[]|null
     * @SerializedName("eans")
     * @Assert\All({
     *   @Assert\Type("string")
     * })
     * @Type("array<string>")
     */
    protected $eans;

    /**
     * A list of ASINs
     *
     * @var string[]|null
     * @SerializedName("asins")
     * @Assert\All({
     *   @Assert\Type("string")
     * })
     * @Type("array<string>")
     */
    protected $asins;

    /**
     * @var string|null
     * @SerializedName("message")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $message;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->upcs = isset($data['upcs']) ? $data['upcs'] : null;
        $this->eans = isset($data['eans']) ? $data['eans'] : null;
        $this->asins = isset($data['asins']) ? $data['asins'] : null;
        $this->message = isset($data['message']) ? $data['message'] : null;
    }

    /**
     * Gets upcs.
     *
     * @return string[]|null
     */
    public function getUpcs(): ?array
    {
        return $this->upcs;
    }

    /**
     * Sets upcs.
     *
     * @param string[]|null $upcs  A list of UPCs
     *
     * @return $this
     */
    public function setUpcs(array $upcs = null): ?array
    {
        $this->upcs = $upcs;

        return $this;
    }

    /**
     * Gets eans.
     *
     * @return string[]|null
     */
    public function getEans(): ?array
    {
        return $this->eans;
    }

    /**
     * Sets eans.
     *
     * @param string[]|null $eans  A list of EANs
     *
     * @return $this
     */
    public function setEans(array $eans = null): ?array
    {
        $this->eans = $eans;

        return $this;
    }

    /**
     * Gets asins.
     *
     * @return string[]|null
     */
    public function getAsins(): ?array
    {
        return $this->asins;
    }

    /**
     * Sets asins.
     *
     * @param string[]|null $asins  A list of ASINs
     *
     * @return $this
     */
    public function setAsins(array $asins = null): ?array
    {
        $this->asins = $asins;

        return $this;
    }

    /**
     * Gets message.
     *
     * @return string|null
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Sets message.
     *
     * @param string|null $message
     *
     * @return $this
     */
    public function setMessage($message = null)
    {
        $this->message = $message;

        return $this;
    }
}


