#import <Foundation/Foundation.h>
#import <JSONModel/JSONValueTransformer.h>

/**
* Barcodable.com API
* Barcodable.com API
*
* OpenAPI spec version: 1.5.0
* Contact: support@barcodable.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface JSONValueTransformer (ISO8601)

@end
