/**
 * Barcodable.com API
 * Barcodable.com API
 *
 * OpenAPI spec version: 1.5.0
 * Contact: support@barcodable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BarcodablecomApi) {
      root.BarcodablecomApi = {};
    }
    root.BarcodablecomApi.Item = factory(root.BarcodablecomApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The Item model module.
   * @module model/Item
   * @version 1.5.0
   */

  /**
   * Constructs a new <code>Item</code>.
   * @alias module:model/Item
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Item</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Item} obj Optional instance to populate.
   * @return {module:model/Item} The populated <code>Item</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('upc')) {
        obj['upc'] = ApiClient.convertToType(data['upc'], 'String');
      }
      if (data.hasOwnProperty('ean')) {
        obj['ean'] = ApiClient.convertToType(data['ean'], 'String');
      }
      if (data.hasOwnProperty('isbn')) {
        obj['isbn'] = ApiClient.convertToType(data['isbn'], 'String');
      }
      if (data.hasOwnProperty('asin')) {
        obj['asin'] = ApiClient.convertToType(data['asin'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('sku')) {
        obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
      }
      if (data.hasOwnProperty('mpn')) {
        obj['mpn'] = ApiClient.convertToType(data['mpn'], 'String');
      }
      if (data.hasOwnProperty('part_number')) {
        obj['part_number'] = ApiClient.convertToType(data['part_number'], 'String');
      }
      if (data.hasOwnProperty('upcs')) {
        obj['upcs'] = ApiClient.convertToType(data['upcs'], ['String']);
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('brand')) {
        obj['brand'] = ApiClient.convertToType(data['brand'], 'String');
      }
      if (data.hasOwnProperty('manufacturer')) {
        obj['manufacturer'] = ApiClient.convertToType(data['manufacturer'], 'String');
      }
      if (data.hasOwnProperty('color')) {
        obj['color'] = ApiClient.convertToType(data['color'], 'String');
      }
      if (data.hasOwnProperty('new_price')) {
        obj['new_price'] = ApiClient.convertToType(data['new_price'], 'Number');
      }
      if (data.hasOwnProperty('used_price')) {
        obj['used_price'] = ApiClient.convertToType(data['used_price'], 'Number');
      }
      if (data.hasOwnProperty('currency_code')) {
        obj['currency_code'] = ApiClient.convertToType(data['currency_code'], 'String');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('features')) {
        obj['features'] = ApiClient.convertToType(data['features'], ['String']);
      }
      if (data.hasOwnProperty('dimensions')) {
        obj['dimensions'] = ApiClient.convertToType(data['dimensions'], [Object]);
      }
      if (data.hasOwnProperty('images')) {
        obj['images'] = ApiClient.convertToType(data['images'], ['String']);
      }
      if (data.hasOwnProperty('matched_items')) {
        obj['matched_items'] = ApiClient.convertToType(data['matched_items'], [Object]);
      }
      if (data.hasOwnProperty('iso_country_codes')) {
        obj['iso_country_codes'] = ApiClient.convertToType(data['iso_country_codes'], ['String']);
      }
      if (data.hasOwnProperty('company_name')) {
        obj['company_name'] = ApiClient.convertToType(data['company_name'], 'String');
      }
      if (data.hasOwnProperty('company_address')) {
        obj['company_address'] = ApiClient.convertToType(data['company_address'], 'String');
      }
      if (data.hasOwnProperty('categories')) {
        obj['categories'] = ApiClient.convertToType(data['categories'], ['String']);
      }
      if (data.hasOwnProperty('category_hierarchies')) {
        obj['category_hierarchies'] = ApiClient.convertToType(data['category_hierarchies'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {String} upc
   */
  exports.prototype['upc'] = undefined;
  /**
   * @member {String} ean
   */
  exports.prototype['ean'] = undefined;
  /**
   * @member {String} isbn
   */
  exports.prototype['isbn'] = undefined;
  /**
   * @member {String} asin
   */
  exports.prototype['asin'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {String} sku
   */
  exports.prototype['sku'] = undefined;
  /**
   * @member {String} mpn
   */
  exports.prototype['mpn'] = undefined;
  /**
   * @member {String} part_number
   */
  exports.prototype['part_number'] = undefined;
  /**
   * A list of matching upc codes.
   * @member {Array.<String>} upcs
   */
  exports.prototype['upcs'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {String} brand
   */
  exports.prototype['brand'] = undefined;
  /**
   * @member {String} manufacturer
   */
  exports.prototype['manufacturer'] = undefined;
  /**
   * @member {String} color
   */
  exports.prototype['color'] = undefined;
  /**
   * @member {Number} new_price
   */
  exports.prototype['new_price'] = undefined;
  /**
   * @member {Number} used_price
   */
  exports.prototype['used_price'] = undefined;
  /**
   * @member {String} currency_code
   */
  exports.prototype['currency_code'] = undefined;
  /**
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * A list of product feature descriptions.
   * @member {Array.<String>} features
   */
  exports.prototype['features'] = undefined;
  /**
   * Product dimensions and weight.  ('meters', 'centimeters', 'millimeters', 'inches', 'feet', 'yards', 'ounces', 'pounds', 'grams', 'milligrams', 'kilograms')
   * @member {Array.<Object>} dimensions
   */
  exports.prototype['dimensions'] = undefined;
  /**
   * A list product images.
   * @member {Array.<String>} images
   */
  exports.prototype['images'] = undefined;
  /**
   * Matched items for this product.
   * @member {Array.<Object>} matched_items
   */
  exports.prototype['matched_items'] = undefined;
  /**
   * A list of country codes from which this item belongs.
   * @member {Array.<String>} iso_country_codes
   */
  exports.prototype['iso_country_codes'] = undefined;
  /**
   * The company name registered to the product's UPC or EAN.
   * @member {String} company_name
   */
  exports.prototype['company_name'] = undefined;
  /**
   * The company address registered to the product's UPC or EAN.
   * @member {String} company_address
   */
  exports.prototype['company_address'] = undefined;
  /**
   * A list of categories for this product.
   * @member {Array.<String>} categories
   */
  exports.prototype['categories'] = undefined;
  /**
   * A list of category hierarchies for this product. Categories are listed in order of generic category to most specific category.
   * @member {Array.<String>} category_hierarchies
   */
  exports.prototype['category_hierarchies'] = undefined;



  return exports;
}));


