/**
 * Barcodable.com API
 * Barcodable.com API
 *
 * OpenAPI spec version: 1.5.0
 * Contact: support@barcodable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAINot_found.h
 *
 * 
 */

#ifndef OAINot_found_H
#define OAINot_found_H

#include <QJsonObject>


#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAINot_found: public OAIObject {
public:
    OAINot_found();
    OAINot_found(QString json);
    ~OAINot_found() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getMessage() const;
    void setMessage(const QString &message);

    qint32 getStatus() const;
    void setStatus(const qint32 &status);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    QString message;
    bool m_message_isSet;
    bool m_message_isValid;
    qint32 status;
    bool m_status_isSet;
    bool m_status_isValid;
};

}

#endif // OAINot_found_H
