/**
* Barcodable.com API
* Barcodable.com API
*
* The version of the OpenAPI document: 1.5.0
* Contact: support@barcodable.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


/**
 * 
 * @param upc 
 * @param ean 
 * @param isbn 
 * @param asin 
 * @param title 
 * @param sku 
 * @param mpn 
 * @param partNumber 
 * @param upcs A list of matching upc codes.
 * @param description 
 * @param brand 
 * @param manufacturer 
 * @param color 
 * @param newPrice 
 * @param usedPrice 
 * @param currencyCode 
 * @param url 
 * @param features A list of product feature descriptions.
 * @param dimensions Product dimensions and weight.  ('meters', 'centimeters', 'millimeters', 'inches', 'feet', 'yards', 'ounces', 'pounds', 'grams', 'milligrams', 'kilograms')
 * @param images A list product images.
 * @param matchedItems Matched items for this product.
 * @param isoCountryCodes A list of country codes from which this item belongs.
 * @param companyName The company name registered to the product's UPC or EAN.
 * @param companyAddress The company address registered to the product's UPC or EAN.
 * @param categories A list of categories for this product.
 * @param categoryHierarchies A list of category hierarchies for this product. Categories are listed in order of generic category to most specific category.
 */
data class Item (
    val upc: kotlin.String? = null,
    val ean: kotlin.String? = null,
    val isbn: kotlin.String? = null,
    val asin: kotlin.String? = null,
    val title: kotlin.String? = null,
    val sku: kotlin.String? = null,
    val mpn: kotlin.String? = null,
    val partNumber: kotlin.String? = null,
    /* A list of matching upc codes. */
    val upcs: kotlin.Array<kotlin.String>? = null,
    val description: kotlin.String? = null,
    val brand: kotlin.String? = null,
    val manufacturer: kotlin.String? = null,
    val color: kotlin.String? = null,
    val newPrice: java.math.BigDecimal? = null,
    val usedPrice: java.math.BigDecimal? = null,
    val currencyCode: kotlin.String? = null,
    val url: kotlin.String? = null,
    /* A list of product feature descriptions. */
    val features: kotlin.Array<kotlin.String>? = null,
    /* Product dimensions and weight.  ('meters', 'centimeters', 'millimeters', 'inches', 'feet', 'yards', 'ounces', 'pounds', 'grams', 'milligrams', 'kilograms') */
    val dimensions: kotlin.Array<kotlin.Any>? = null,
    /* A list product images. */
    val images: kotlin.Array<kotlin.String>? = null,
    /* Matched items for this product. */
    val matchedItems: kotlin.Array<kotlin.Any>? = null,
    /* A list of country codes from which this item belongs. */
    val isoCountryCodes: kotlin.Array<kotlin.String>? = null,
    /* The company name registered to the product's UPC or EAN. */
    val companyName: kotlin.String? = null,
    /* The company address registered to the product's UPC or EAN. */
    val companyAddress: kotlin.String? = null,
    /* A list of categories for this product. */
    val categories: kotlin.Array<kotlin.String>? = null,
    /* A list of category hierarchies for this product. Categories are listed in order of generic category to most specific category. */
    val categoryHierarchies: kotlin.Array<kotlin.String>? = null
) 

