-module(openapi_item).

-export([encode/1]).

-export_type([openapi_item/0]).

-type openapi_item() ::
    #{ 'upc' => binary(),
       'ean' => binary(),
       'isbn' => binary(),
       'asin' => binary(),
       'title' => binary(),
       'sku' => binary(),
       'mpn' => binary(),
       'part_number' => binary(),
       'upcs' => list(),
       'description' => binary(),
       'brand' => binary(),
       'manufacturer' => binary(),
       'color' => binary(),
       'new_price' => integer(),
       'used_price' => integer(),
       'currency_code' => binary(),
       'url' => binary(),
       'features' => list(),
       'dimensions' => list(),
       'images' => list(),
       'matched_items' => list(),
       'iso_country_codes' => list(),
       'company_name' => binary(),
       'company_address' => binary(),
       'categories' => list(),
       'category_hierarchies' => list()
     }.

encode(#{ 'upc' := Upc,
          'ean' := Ean,
          'isbn' := Isbn,
          'asin' := Asin,
          'title' := Title,
          'sku' := Sku,
          'mpn' := Mpn,
          'part_number' := PartNumber,
          'upcs' := Upcs,
          'description' := Description,
          'brand' := Brand,
          'manufacturer' := Manufacturer,
          'color' := Color,
          'new_price' := NewPrice,
          'used_price' := UsedPrice,
          'currency_code' := CurrencyCode,
          'url' := Url,
          'features' := Features,
          'dimensions' := Dimensions,
          'images' := Images,
          'matched_items' := MatchedItems,
          'iso_country_codes' := IsoCountryCodes,
          'company_name' := CompanyName,
          'company_address' := CompanyAddress,
          'categories' := Categories,
          'category_hierarchies' := CategoryHierarchies
        }) ->
    #{ 'upc' => Upc,
       'ean' => Ean,
       'isbn' => Isbn,
       'asin' => Asin,
       'title' => Title,
       'sku' => Sku,
       'mpn' => Mpn,
       'part_number' => PartNumber,
       'upcs' => Upcs,
       'description' => Description,
       'brand' => Brand,
       'manufacturer' => Manufacturer,
       'color' => Color,
       'new_price' => NewPrice,
       'used_price' => UsedPrice,
       'currency_code' => CurrencyCode,
       'url' => Url,
       'features' => Features,
       'dimensions' => Dimensions,
       'images' => Images,
       'matched_items' => MatchedItems,
       'iso_country_codes' => IsoCountryCodes,
       'company_name' => CompanyName,
       'company_address' => CompanyAddress,
       'categories' => Categories,
       'category_hierarchies' => CategoryHierarchies
     }.
