// tslint:disable
/**
 * Barcodable.com API
 * Barcodable.com API
 *
 * OpenAPI spec version: 1.5.0
 * Contact: support@barcodable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse400
 */
export interface InlineResponse400 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse400
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse400
     */
    status?: number;
}

export function InlineResponse400FromJSON(json: any): InlineResponse400 {
    return {
        'message': !exists(json, 'message') ? undefined : json['message'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function InlineResponse400ToJSON(value?: InlineResponse400): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'message': value.message,
        'status': value.status,
    };
}


