/**
 * Barcodable.com API
 * Barcodable.com API
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: support@barcodable.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "Not_found.h"

#include <string>
#include <sstream>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace org {
namespace openapitools {
namespace server {
namespace model {

Not_found::Not_found()
{
	m_Message = "";
	m_Status = 0;
}

Not_found::~Not_found()
{
}

std::string Not_found::toJsonString(bool prettyJson)
{
	std::stringstream ss;
	write_json(ss, this->toPropertyTree(), prettyJson);
	return ss.str();
}

void Not_found::fromJsonString(std::string const& jsonString)
{
	std::stringstream ss(jsonString);
	ptree pt;
	read_json(ss,pt);
	this->fromPropertyTree(pt);
}

ptree Not_found::toPropertyTree()
{
	ptree pt;
	ptree tmp_node;
	pt.put("message", m_Message);
	pt.put("status", m_Status);
	return pt;
}

void Not_found::fromPropertyTree(ptree const &pt)
{
	ptree tmp_node;
	m_Message = pt.get("message", "");
	m_Status = pt.get("status", 0);
}

std::string Not_found::getMessage() const
{
    return m_Message;
}
void Not_found::setMessage(std::string value)
{
	m_Message = value;
}
int32_t Not_found::getStatus() const
{
    return m_Status;
}
void Not_found::setStatus(int32_t value)
{
	m_Status = value;
}

}
}
}
}

