# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class NotFound(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message: str=None, status: int=None):
        """NotFound - a model defined in OpenAPI

        :param message: The message of this NotFound.
        :param status: The status of this NotFound.
        """
        self.openapi_types = {
            'message': str,
            'status': int
        }

        self.attribute_map = {
            'message': 'message',
            'status': 'status'
        }

        self._message = message
        self._status = status

    @classmethod
    def from_dict(cls, dikt: dict) -> 'NotFound':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The not_found of this NotFound.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self):
        """Gets the message of this NotFound.


        :return: The message of this NotFound.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this NotFound.


        :param message: The message of this NotFound.
        :type message: str
        """

        self._message = message

    @property
    def status(self):
        """Gets the status of this NotFound.


        :return: The status of this NotFound.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this NotFound.


        :param status: The status of this NotFound.
        :type status: int
        """

        self._status = status
