/**
* Barcodable.com API
* Barcodable.com API
*
* The version of the OpenAPI document: 1.5.0
* Contact: support@barcodable.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Inline_response_200.h
 *
 * 
 */

#ifndef Inline_response_200_H_
#define Inline_response_200_H_


#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Inline_response_200
{
public:
    Inline_response_200();
    virtual ~Inline_response_200();

    void validate();

    /////////////////////////////////////////////
    /// Inline_response_200 members

    /// <summary>
    /// A list of UPCs
    /// </summary>
    std::vector<std::string>& getUpcs();
    void setUpcs(std::vector<std::string> const& value);
    bool upcsIsSet() const;
    void unsetUpcs();
    /// <summary>
    /// A list of EANs
    /// </summary>
    std::vector<std::string>& getEans();
    void setEans(std::vector<std::string> const& value);
    bool eansIsSet() const;
    void unsetEans();
    /// <summary>
    /// A list of ASINs
    /// </summary>
    std::vector<std::string>& getAsins();
    void setAsins(std::vector<std::string> const& value);
    bool asinsIsSet() const;
    void unsetAsins();
    /// <summary>
    /// 
    /// </summary>
    std::string getMessage() const;
    void setMessage(std::string const& value);
    bool messageIsSet() const;
    void unsetMessage();

    friend void to_json(nlohmann::json& j, const Inline_response_200& o);
    friend void from_json(const nlohmann::json& j, Inline_response_200& o);
protected:
    std::vector<std::string> m_Upcs;
    bool m_UpcsIsSet;
    std::vector<std::string> m_Eans;
    bool m_EansIsSet;
    std::vector<std::string> m_Asins;
    bool m_AsinsIsSet;
    std::string m_Message;
    bool m_MessageIsSet;
};

}
}
}
}

#endif /* Inline_response_200_H_ */
