/**
* Barcodable.com API
* Barcodable.com API
*
* The version of the OpenAPI document: 1.5.0
* Contact: support@barcodable.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Not_found.h
 *
 * 
 */

#ifndef Not_found_H_
#define Not_found_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Not_found
{
public:
    Not_found();
    virtual ~Not_found();

    void validate();

    /////////////////////////////////////////////
    /// Not_found members

    /// <summary>
    /// 
    /// </summary>
    std::string getMessage() const;
    void setMessage(std::string const& value);
    bool messageIsSet() const;
    void unsetMessage();
    /// <summary>
    /// 
    /// </summary>
    int32_t getStatus() const;
    void setStatus(int32_t const value);
    bool statusIsSet() const;
    void unsetStatus();

    friend void to_json(nlohmann::json& j, const Not_found& o);
    friend void from_json(const nlohmann::json& j, Not_found& o);
protected:
    std::string m_Message;
    bool m_MessageIsSet;
    int32_t m_Status;
    bool m_StatusIsSet;
};

}
}
}
}

#endif /* Not_found_H_ */
