/* 
 * Barcodable.com API
 *
 * Barcodable.com API
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: support@barcodable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ProductConversionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ProductConversionApiTests : IDisposable
    {
        private ProductConversionApi instance;

        public ProductConversionApiTests()
        {
            instance = new ProductConversionApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductConversionApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ProductConversionApi
            //Assert.IsType(typeof(ProductConversionApi), instance, "instance is a ProductConversionApi");
        }

        
        /// <summary>
        /// Test ConvertCode
        /// </summary>
        [Fact]
        public void ConvertCodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string upcEanAsin = null;
            //var response = instance.ConvertCode(upcEanAsin);
            //Assert.IsType<InlineResponse200> (response, "response is InlineResponse200");
        }
        
    }

}
