# coding: utf-8

"""
    Barcodable.com API

    Barcodable.com API  # noqa: E501

    OpenAPI spec version: 1.5.0
    Contact: support@barcodable.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from openapi_client.api_client import ApiClient


class ProductLookupApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_item_by_asin(self, asin, **kwargs):  # noqa: E501
        """Find item by asin code  # noqa: E501

        Returns a single item  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_item_by_asin(asin, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str asin: ASIN code of item to return (required)
        :return: Item
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_item_by_asin_with_http_info(asin, **kwargs)  # noqa: E501
        else:
            (data) = self.get_item_by_asin_with_http_info(asin, **kwargs)  # noqa: E501
            return data

    def get_item_by_asin_with_http_info(self, asin, **kwargs):  # noqa: E501
        """Find item by asin code  # noqa: E501

        Returns a single item  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_item_by_asin_with_http_info(asin, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str asin: ASIN code of item to return (required)
        :return: Item
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['asin']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_item_by_asin" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'asin' is set
        if ('asin' not in local_var_params or
                local_var_params['asin'] is None):
            raise ValueError("Missing the required parameter `asin` when calling `get_item_by_asin`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'asin' in local_var_params:
            path_params['asin'] = local_var_params['asin']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/asin/{asin}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Item',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_item_by_ean(self, ean, **kwargs):  # noqa: E501
        """Find item by UPC code  # noqa: E501

        Returns a single item  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_item_by_ean(ean, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str ean: EAN code of item to return (required)
        :return: Item
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_item_by_ean_with_http_info(ean, **kwargs)  # noqa: E501
        else:
            (data) = self.get_item_by_ean_with_http_info(ean, **kwargs)  # noqa: E501
            return data

    def get_item_by_ean_with_http_info(self, ean, **kwargs):  # noqa: E501
        """Find item by UPC code  # noqa: E501

        Returns a single item  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_item_by_ean_with_http_info(ean, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str ean: EAN code of item to return (required)
        :return: Item
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['ean']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_item_by_ean" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'ean' is set
        if ('ean' not in local_var_params or
                local_var_params['ean'] is None):
            raise ValueError("Missing the required parameter `ean` when calling `get_item_by_ean`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ean' in local_var_params:
            path_params['ean'] = local_var_params['ean']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/ean/{ean}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Item',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_item_by_upc(self, upc, **kwargs):  # noqa: E501
        """Find item by UPC code  # noqa: E501

        Returns a single item  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_item_by_upc(upc, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str upc: UPC code of item to return (required)
        :return: Item
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_item_by_upc_with_http_info(upc, **kwargs)  # noqa: E501
        else:
            (data) = self.get_item_by_upc_with_http_info(upc, **kwargs)  # noqa: E501
            return data

    def get_item_by_upc_with_http_info(self, upc, **kwargs):  # noqa: E501
        """Find item by UPC code  # noqa: E501

        Returns a single item  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_item_by_upc_with_http_info(upc, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str upc: UPC code of item to return (required)
        :return: Item
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['upc']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_item_by_upc" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'upc' is set
        if ('upc' not in local_var_params or
                local_var_params['upc'] is None):
            raise ValueError("Missing the required parameter `upc` when calling `get_item_by_upc`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'upc' in local_var_params:
            path_params['upc'] = local_var_params['upc']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/upc/{upc}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Item',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
