<?php
/**
 * InlineResponse200
 *
 * PHP version 7
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

/**
 * InlineResponse200
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class InlineResponse200
{
    
    /** @var string[] $upcs A list of UPCs*/
    private $upcs;
    
    /** @var string[] $eans A list of EANs*/
    private $eans;
    
    /** @var string[] $asins A list of ASINs*/
    private $asins;
    
    /** @var string $message */
    private $message;
}
