/**
 * Barcodable.com API
 * Barcodable.com API
 *
 * OpenAPI spec version: 1.5.0
 * Contact: support@barcodable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse200 {
  
  @SerializedName("upcs")
  private List<String> upcs = null;
  @SerializedName("eans")
  private List<String> eans = null;
  @SerializedName("asins")
  private List<String> asins = null;
  @SerializedName("message")
  private String message = null;

  /**
   * A list of UPCs
   **/
  @ApiModelProperty(value = "A list of UPCs")
  public List<String> getUpcs() {
    return upcs;
  }
  public void setUpcs(List<String> upcs) {
    this.upcs = upcs;
  }

  /**
   * A list of EANs
   **/
  @ApiModelProperty(value = "A list of EANs")
  public List<String> getEans() {
    return eans;
  }
  public void setEans(List<String> eans) {
    this.eans = eans;
  }

  /**
   * A list of ASINs
   **/
  @ApiModelProperty(value = "A list of ASINs")
  public List<String> getAsins() {
    return asins;
  }
  public void setAsins(List<String> asins) {
    this.asins = asins;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }
  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return (this.upcs == null ? inlineResponse200.upcs == null : this.upcs.equals(inlineResponse200.upcs)) &&
        (this.eans == null ? inlineResponse200.eans == null : this.eans.equals(inlineResponse200.eans)) &&
        (this.asins == null ? inlineResponse200.asins == null : this.asins.equals(inlineResponse200.asins)) &&
        (this.message == null ? inlineResponse200.message == null : this.message.equals(inlineResponse200.message));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.upcs == null ? 0: this.upcs.hashCode());
    result = 31 * result + (this.eans == null ? 0: this.eans.hashCode());
    result = 31 * result + (this.asins == null ? 0: this.asins.hashCode());
    result = 31 * result + (this.message == null ? 0: this.message.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("  upcs: ").append(upcs).append("\n");
    sb.append("  eans: ").append(eans).append("\n");
    sb.append("  asins: ").append(asins).append("\n");
    sb.append("  message: ").append(message).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
