/*
 * Barcodable.com API
 * Barcodable.com API
 *
 * OpenAPI spec version: 1.5.0
 * Contact: support@barcodable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * OpenAPI generator version: 4.3.0
 */


import http from "k6/http";
import { group, check, sleep } from "k6";

const BASE_URL = "https://www.barcodable.com";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function() {
    group("/api/v1/upc/{upc}", () => {
        let upc = "TODO_EDIT_THE_UPC";
        let url = BASE_URL + `/api/v1/upc/${upc}`;
        // Request No. 1
        let request = http.get(url);
        check(request, {
            "successful operation": (r) => r.status === 200
        });
        sleep(SLEEP_DURATION);
    });
    group("/api/v1/ean/{ean}", () => {
        let ean = "TODO_EDIT_THE_EAN";
        let url = BASE_URL + `/api/v1/ean/${ean}`;
        // Request No. 1
        let request = http.get(url);
        check(request, {
            "successful operation": (r) => r.status === 200
        });
        sleep(SLEEP_DURATION);
    });
    group("/api/v1/asin/{asin}", () => {
        let asin = "TODO_EDIT_THE_ASIN";
        let url = BASE_URL + `/api/v1/asin/${asin}`;
        // Request No. 1
        let request = http.get(url);
        check(request, {
            "successful operation": (r) => r.status === 200
        });
        sleep(SLEEP_DURATION);
    });
    group("/api/v1/convert/{upc | ean | asin}", () => {
        let upcEanAsin = "TODO_EDIT_THE_UPC | EAN | ASIN";
        let url = BASE_URL + `/api/v1/convert/${upc | ean | asin}`;
        // Request No. 1
        let request = http.get(url);
        check(request, {
            "successful operation": (r) => r.status === 200
        });
        sleep(SLEEP_DURATION);
    });
}
